### api/create
POST http://localhost:1337/api/create HTTP/1.1
Accept: application/json

{
  "age": 999,
  "someData": "content"
}

### Get hello
GET http://localhost:1337/hello HTTP/1.1
Accept: application/json

### Get hello
GET http://localhost:1337/api/method1 HTTP/1.1
Accept: application/json

### Get users
GET http://localhost:1337/api/users HTTP/1.1
Accept: application/json

### Get bad route
GET http://localhost:1337/wrong HTTP/1.1
Accept: application/json
