### /api/records CREATE
POST http://localhost:5000//api/records HTTP/1.1
Accept: application/json

{
  "age": 999,
  "someData": "content"
}

### /api/records POPULATE
GET http://localhost:5000//api/records HTTP/1.1
Accept: application/json

### Get bad route
GET http://localhost:5000/no-such-route HTTP/1.1
Accept: application/json
